[phases.setup]
providers = ["node"]

[phases.install]
cmds = [
    "npm install -g corepack",
    "corepack enable",
    "corepack prepare pnpm@9.1.0 --activate", 
    "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm payload migrate && pnpm start:server"